### ISSUE TITLE
Error converting value \"Clear\" to type 'System.Nullable`1[IsgWebApi.SecurityGraphModel.TlpLevel]'

### ISSUE THREAD

**Issue by infernuxmonster** [cudeso/misp2sentinel#15]
## Description

After upgrading MISP to version v2.4.171(https://github.com/MISP/MISP/releases/tag/v2.4.171) we have been having issues when pushing indicators with the script. From a test I did just now, we get the following results:

```
7502 indicators are parsed from misp events. Only those that do not exist in Microsoft Graph Security will be sent.

current batch took:     0.23 seconds
script finished running

total indicators sent:       76
total response success:       0
total response error:        76
total indicators deleted:     0
```

This was with the current filters and options configured (limit is there just for testing):
``` 
targetProduct = 'Azure Sentinel'
misp_event_filters = {
    'timestamp' : "1d",
    'limit' : 1,
    'enforce_warninglist' : 1
}

action = 'alert'
passiveOnly = False
days_to_expire = 14
misp_key = retrieved_mispkey.value
misp_domain = 'misp.dummydomain.com'
misp_verifycert = True

network_ignore_direction = True

verbose_log = True
write_post_json = True
misp_ignore_localtags = True
defaultConfidenceLevel = 50
```

When we drop the limit we can see that about 10% of all indicators are sent, but the rest throw errors.

## Errors

All errors are similar:

```
{"code": "", "message": "Error converting value \"Clear\" to type 'System.Nullable`1[IsgWebApi.SecurityGraphModel.TlpLevel]'. Path '[0].tlpLevel', line 7, position 23.", "innerError": {"date": "2023-05-31T07:17:03", "request-id": "47b6113b-b939-4897-97bc-1cab2607dc73", "client-request-id": "47b6113b-b939-4897-97bc-1cab2607dc73"}}
```

Not sure how to fix - this is a base MISP install, script is the vanilla implementation and tags are added to the event like they were before the errors started occuring.

**Comment by infernuxmonster** [comment]
Even when doing `'not_tags' : ["tlp:clear"]` in the filter it still throws the same error.

**Comment by cudeso** [comment]
This is due to the fact that Microsoft Graph API does not support TLP:Clear for indicators (https://learn.microsoft.com/en-us/graph/api/resources/tiindicator?view=graph-rest-beta#tlplevel-values).
You can ignore the tlp-clear events with `"!tlp:clear"`. For example `"tags": ["coa:detect=\"other\"","!tlp:clear"]`.

I'll add a conversion from clear to white in an updated version.
