### ISSUE TITLE
IPs in CIDR Format Fail to Upload

### ISSUE THREAD

**Issue by NickS-2022** [cudeso/misp2sentinel#21]
I'm ingesting Threat Intelligence Indicators  from a 3rd party MISP instance and I'm seeing a number of failures.

The error message is x.x.x.x/xx is not a valid IP address.

Looking at an example on their MISP instance the address is of type IP: IP Dst.  So MISP accepts CIDR format IP addresses for this type, but the integration is expecting just a single IP.  Ironically, a lot of them are just /32 so no reason to use the CIDR format, but they say it is a valid and that the integration script needs to handle this.

I see that Sentinel does have a CIDR Block field so just wondering if that field should be used if the field is detected as containing a CIDR format.

**Comment by cudeso** [comment]
Hello @NickS-2022 
In the new approach, using the [Threat Intelligence Upload Indicators API ](https://learn.microsoft.com/en-us/azure/sentinel/data-connectors/threat-intelligence-upload-indicators-api) this is solved. The Sentinel API accepts CIDR notation (coming from STIX).
The new approach is currently in the branch https://github.com/cudeso/misp2sentinel/tree/upload_indicators_api

An simple fix for the Microsoft Graph API would be to detect if there's a "/" in the IP, then either use networkSourceCidrBlock or networkSourceIPv4 (or networkDestinationCidrBlock / networkDestinationIPv4).

I'll attempt to address this shortly, but in the mean you can have a look "near" line https://github.com/cudeso/misp2sentinel/blob/cd6443646298f695b420b81b60d01f1764ea2c55/RequestObject.py#L57 ; that's where it should be addressed.

**Comment by cudeso** [comment]
The Upload Indicators branch contains a fix that works for both the old Graph API and Upload Indicators API. Maybe you can give it a try? https://github.com/cudeso/misp2sentinel/tree/upload_indicators_api
Do not forget to bring your configuration in line with https://github.com/cudeso/misp2sentinel/blob/upload_indicators_api/config.py.default
