### ISSUE TITLE
MISP to Upload Indicator API - No log file configuration setting found (log_file).

### ISSUE THREAD

**Issue by PiusO** [cudeso/misp2sentinel#22]
First of all thank you for promptly putting together a new script for the new TI connector and Upload Indicator API.

After applying all steps from the previous way of doing things -  misp to sentinel using MGS document. 
This time modifying the new config.py accordingly and making sure the other files match this directory (although cloning pulled in the older scripts.)

When i run 'python3 script.py' i get the following error:

script.py:1: DeprecationWarning: 
As our baseline system is the latest Ubuntu LTS, and Ubuntu LTS 22.04 has Python 3.10 available,
we will officially deprecate python versions below 3.10 on January 1st 2024.
**Please update your codebase.**
  from pymisp import ExpandedPyMISP
Exiting. No log file configuration setting found (log_file).   

Any idea what's going on?

**Comment by cudeso** [comment]
In this version I started replacing the simple "print" commands with logging the progress to a logfile. 
You need to set the value `log_file` in `config.py` to a file location where the user that executes the script can write to (for example `/tmp/misp2sentinel.log` or `/var/log/misp/misp2sentinel.log`).
