### ISSUE TITLE
Upload_indicators_API returning 'Valid_until not set' errors

### ISSUE THREAD

**Issue by Parasdeepkohli** [cudeso/misp2sentinel#28]
Hi,

I attempted to run the script for pushing indicators to the Upload_indicators_API (because the current connector is being deprecated by Microsoft) and ran into the following error:

`misp2sentinel - ERROR - Skipping indicator because valid_until was not set by MISP/MISP2Sentinel indicator-<indicator>`

This error message was logged for every indicator I tried to push, leading to 0 indicators being sent.

**Comment by cudeso** [comment]
Can you try updating your configuration to the new format? See an example at https://github.com/cudeso/misp2sentinel/blob/upload_indicators_api/config.py.default

**Comment by Parasdeepkohli** [comment]
I updated the configuration to the new format and running script.py leads to the this error now:

Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.173 - Python 3.11', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Cookie': 'CAKEPHP=rpmu30tps28eo9tnp7qov7ctq0', 'Content-Length': '332', 'content-type': 'application/json'}
Request body:
{"returnFormat": "stix2", "page": 2, "limit": 50, "eventid": ["6642"], "withAttachments": 0, "metadata": 0, "enforceWarninglist": 0, "includeEventUuid": 0, "includeEventTags": 0, "sgReferenceOnly": 0, "includeContext": 0, "headerless": 0, "includeSightings": 0, "includeDecayScore": 0, "includeCorrelations": 0, "excludeDecayed": 0}
Response (if any):
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/restSearch"}


You can ignore 'An Internal Error Has Occurred' message thrown by MISP.
The MISP STIX export does not return the number of page results. We query for results until we get an error.
Also see: https://github.com/MISP/misp-stix/issues/44

**Comment by lnfernux** [comment]
> I updated the configuration to the new format and running script.py leads to the this error now:
> 
> Unknown error: the response is not in JSON. Something is broken server-side, please send us everything that follows (careful with the auth key): Request headers: {'User-Agent': 'PyMISP 2.4.173 - Python 3.11', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Cookie': 'CAKEPHP=rpmu30tps28eo9tnp7qov7ctq0', 'Content-Length': '332', 'content-type': 'application/json'} Request body: {"returnFormat": "stix2", "page": 2, "limit": 50, "eventid": ["6642"], "withAttachments": 0, "metadata": 0, "enforceWarninglist": 0, "includeEventUuid": 0, "includeEventTags": 0, "sgReferenceOnly": 0, "includeContext": 0, "headerless": 0, "includeSightings": 0, "includeDecayScore": 0, "includeCorrelations": 0, "excludeDecayed": 0} Response (if any): {"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"/events/restSearch"}
> 
> You can ignore 'An Internal Error Has Occurred' message thrown by MISP. The MISP STIX export does not return the number of page results. We query for results until we get an error. Also see: [MISP/misp-stix#44](https://github.com/MISP/misp-stix/issues/44)

Yes, that's expected. I think the newest push to the upload_indicators branch will resolve this issue, at least it did for me. Have you tested after the newest update? 👍🏻

**Comment by cudeso** [comment]
There's an update for the documentation and for the script that should fix this exception. Basically it now uses misp-stix, instead of relying on the STIX responses from the MISP server. The integration now requires `misp-stix` (it's part of the requirements file). You can also manually add it to your Python virtual environment with `pip install misp-stix`.

**Comment by Parasdeepkohli** [comment]
Thanks for the help, cudeso and Infernux! The script seems to be working as intended with the newest push.
