### ISSUE TITLE
No output when running script.py

### ISSUE THREAD

**Issue by aliman53** [cudeso/misp2sentinel#30]
Hi Cudeso,

I have switched over to the new upload indicators API and am testing the new set-up. I have followed the documentation and am pretty sure I have configured everything correctly in Azure and config.py.

Issue:
When running script.py the only output shown is 'clear existing indicators hash':
![image](https://github.com/cudeso/misp2sentinel/assets/130716674/bd63f8f4-a8e2-4c8e-ac26-22f86721d9c8)

It appears that no IOCs are being parsed through the API. 
I checked the logs in /tmp/misp2sentinel.log but does not provide much info as to what could be wrong. 

Any recommendations on how I could further trouble shoot this or if you have come across this issue before?

**Comment by cudeso** [comment]
Hello. That line of code does not exist in the Upload Indicators branch > https://github.com/cudeso/misp2sentinel/blob/upload_indicators_api/RequestManager.py
It does exist in the main branch though. I think you're branch is not set to "upload_indicators_api". 

Check with `git branch`. Switch branches with `git checkout upload_indicators_api`

**Comment by aliman53** [comment]
Hi thanks, I switched branch and that line of code is now gone but still have the same issue of not having a response when running the script.

![image](https://github.com/cudeso/misp2sentinel/assets/130716674/c1ed22f8-a4a6-4563-ab5f-2883207c7ca0)
