### ISSUE TITLE
Unecessary api permissions

### ISSUE THREAD

**Issue by lnfernux** [cudeso/misp2sentinel#31]
In README.MD under Installation - Azure - Azure App Registration, the following is not needed anymore if using upload indicators api:

6. Under **API permissions** (left pane), choose **Add a permission > Microsoft Graph**.
7. Under **Application Permissions**, add **ThreatIndicators.ReadWrite.OwnedBy**.
8. Then grant **consent** for the new permissions via **Grant admin consent for Standaardmap** (*Standaardmap* is replaced with your local tenant setting). Without the consent the application will not have sufficient permissions.

According to this article:

https://learn.microsoft.com/en-us/azure/sentinel/connect-threat-intelligence-upload-api#register-an-azure-ad-application

**Comment by cudeso** [comment]
Fixed with https://github.com/cudeso/misp2sentinel/commit/711815db2a830f55739c0c2cda7eaf2b8a2919a7
