### ISSUE TITLE
Upload indicators API - MISP to MDE

### ISSUE THREAD

**Issue by aliman53** [cudeso/misp2sentinel#42]
Hi Cudeso, 

Does the new script/API allow for sending indicators to Microsoft Defender ? The old API scripts contained the field 'target product' which allows to control between Sentinel and Defender but I do not see something similar to this in the new scripts.

**Comment by cudeso** [comment]
Hello,

The new Microsoft Upload Indicators API only -as far as I can check- supports uploading indicators to Sentinel.
It might be a good addition for a next version. I added this issue to keep track https://github.com/cudeso/misp2sentinel/issues/44
Note that from https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/post-ti-indicator?view=o365-worldwide
```
Limitations
    Rate limitations for this API are 100 calls per minute and 1500 calls per hour.
    There is a limit of 15,000 active indicators per tenant.
```

**Comment by cudeso** [comment]
Track in #44
