### ISSUE TITLE
Consider adding code to upload indicators to Defender

### ISSUE THREAD

**Issue by cudeso** [cudeso/misp2sentinel#44]
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/post-ti-indicator?view=o365-worldwide

**Comment by lnfernux** [comment]
Isn't this supported by Graph API still for Defender?

**Comment by cudeso** [comment]
Right, have to check this or if Graph API is also replaced for Defender.

**Comment by lnfernux** [comment]
It's not at the moment, so the old version of the script still works for this.
