### ISSUE TITLE
_get_request_hash() doesn't work as expected

### ISSUE THREAD

**Issue by k4otix** [cudeso/misp2sentinel#5]
The current implementation of the function to create the request hash results in a different value every time the script is run (see https://stackoverflow.com/questions/27522626/hash-function-in-python-3-3-returns-different-results-between-sessions).

Every time I ran the script, it would think all of the indicators were new, and do a bulk delete of all the "old" indicators since none would be popped from `self.hash_of_indicators_to_delete`.

I'll open a PR for the version of the function I implemented, feel free to merge if you think it is appropriate!

**Comment by cudeso** [comment]
Indeed. Good catch, I merged the PR. Thank you!
