### ISSUE TITLE
Issue when executing script.py

### ISSUE THREAD

**Issue by cristiancamps93** [cudeso/misp2sentinel#58]
Greetings,

I am finding some issues when trying to execute script.py in a Ubuntu 20.04.

After configuring config.py.default everything seems to be perfect. But when executing the script under python3 I get the following error message:
___________________________________________________________

(sentinel) misp@misp:~/misp2sentinel$ python3 script.py
script.py:1: DeprecationWarning:
As our baseline system is the latest Ubuntu LTS, and Ubuntu LTS 22.04 has Python 3.10 available,
we will officially deprecate python versions below 3.10 on January 1st 2024.
**Please update your codebase.**
  from pymisp import *
Traceback (most recent call last):
  File "script.py", line 2, in <module>
    import config
  File "/home/misp/misp2sentinel/config.py", line 15, in <module>
    retrieved_mispkey = client.get_secret('Ki^8CdiJ)24GKJ3E=ptRQpzw.}$Sf[sHE6+039uEqhJ{g.sedOt0M%LPp#eu')
  File "/home/misp/misp2sentinel/sentinel/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/misp/misp2sentinel/sentinel/lib/python3.8/site-packages/azure/keyvault/secrets/_client.py", line 72, in get_secret
    bundle = self._client.get_secret(
  File "/home/misp/misp2sentinel/sentinel/lib/python3.8/site-packages/azure/keyvault/secrets/_generated/_operations_mixin.py", line 1640, in get_secret
    return mixin_instance.get_secret(vault_base_url, secret_name, secret_version, **kwargs)
  File "/home/misp/misp2sentinel/sentinel/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/misp/misp2sentinel/sentinel/lib/python3.8/site-packages/azure/keyvault/secrets/_generated/v7_4/operations/_key_vault_client_operations.py", line 767, in get_secret
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/misp/misp2sentinel/sentinel/lib/python3.8/site-packages/azure/core/exceptions.py", line 163, in map_error
    error = error_type(response=response)
  File "/home/misp/misp2sentinel/sentinel/lib/python3.8/site-packages/azure/keyvault/secrets/_shared/exceptions.py", line 23, in _get_exception_for_key_vault_error
    message = f"({body['error']['code']}) {body['error']['message']}"  # type: Optional[str]
TypeError: string indices must be integers

___________________________________________________________

I've reviewed the config file looking for typos but everything seems to be perfect:

_# Code for supporting storage of secrets in key vault (only works for VMs running on Azure)
import os
from azure.keyvault.secrets import SecretClient
from azure.identity import DefaultAzureCredential

_# Key vault section
keyVaultName = "misp-keys"
KVUri = f"https://misp-sentinel-keyvault.vault.azure.net"

_# Log in with the virtual machines managed identity
credential = DefaultAzureCredential()
client = SecretClient(vault_url=KVUri, credential=credential)

_# Retrieve values from KV (client secret, MISP-key most importantly)
retrieved_mispkey = client.get_secret('{hidden}')
retrieved_clientsecret = client.get_secret('{hidden}')

_# Set values with
_# misp_key = retrieved_mispkey.value
_# 'client_secret': retrieved_clientsecret.value

_####
_# Microsoft section
_#
ms_auth = {
    'tenant': '{hidden}',
    'client_id': '{hidden}',
    'client_secret': '{hidden}',
    'graph_api': True,                                 # Set to False to use Upload Indicators API
    #'scope': 'https://graph.microsoft.com/.default',   # Scope for GraphAPI
    'scope': 'https://management.azure.com/.default',   # Scope for Upload Indicators API
    'workspace_id': '{hidden}'
}

ms_passiveonly = False              # Graph API only
ms_action = 'alert'                 # Graph API only

ms_api_version = "2022-07-01"       # Upload Indicators API version
ms_max_indicators_request = 100     # Upload Indicators API: Throttle max: 100 indicators per request
ms_max_requests_minute = 100        # Upload Indicators API: Throttle max: 100 requests per minute

_####
_# MISP section
misp_key = '{hidden}'
misp_domain = 'https://{hidden}'
misp_verifycert = False

misp_event_filters = {
    "published": 1,
    "tags": [ "workflow:state=\"complete\""],
    "enforceWarninglist": True,
    "includeEventTags": True,
    "publish_timestamp": "14d",
}

misp_event_limit_per_page = 100     # Upload Indicators API: Limit memory use when querying MISP for STIX packages

_####
_# Integration settings

ignore_localtags = True             # Graph API only
network_ignore_direction = True     # Graph API only

default_confidence = 90             # Sentinel default confidence level of indicator

days_to_expire = 50                 # Graph API and Upload Indicators
days_to_expire_start = "current_date" # Upload Indicators API only. Start counting from "valid_from" | "current_date" ;
days_to_expire_mapping = {          # Upload indicators API only. Mapping for expiration of specific indicator types
                    "ipv4-addr": 150,
                    "ipv6-addr": 150,
                    "domain-name": 300,
                    "url": 400,
                }

log_file = "/tmp/misp2sentinel.log"
write_post_json = False             # Graph API only
verbose_log = False
write_parsed_indicators = False      # Upload Indicators only

Thanks in advance.

**Comment by lululemon-harry** [comment]
Hello. Was this bug resolved ? I was looking into getting this integration working. And, have stumbled on this bug too.

**Comment by cudeso** [comment]
Hello @lululemon-harry , I have not been able to look into it more closely.
Are you using the latest version / commit?
Can you paste the exact -anonimised- output for further debugging.

**Comment by lululemon-harry** [comment]
@cudeso added the code below, it shows up when you run script.py. The script still seems to run fine. But, the code for the script should be updated to meet the new standard.

`
ubuntu@ip-10-1-1-10:~/bin/MISP/misp2sentinel$ python3 script.py
script.py:1: DeprecationWarning:
As our baseline system is the latest Ubuntu LTS, and Ubuntu LTS 22.04 has Python 3.10 available,
we will officially deprecate python versions below 3.10 on January 1st 2024.
**Please update your codebase.**
  from pymisp import *
ubuntu@ip-10-1-1-10:~/bin/MISP/misp2sentinel$ 
`

**Comment by cudeso** [comment]
Hi @lululemon-harry ; this error is raised via PyMISP (https://github.com/MISP/PyMISP/blob/main/pymisp/__init__.py#L19) and is because you are running an older version of Python on your system. Upgrade the Python version to 3.10 and the warning goes away.

**Comment by cudeso** [comment]
Closing pending feedback
