### ISSUE TITLE
Include more descriptive property names

### ISSUE THREAD

**Issue by Kaloszer** [cudeso/misp2sentinel#62]
It would be nice to see an example with '''actual''' placeholder values already placed in the config.py.
 
For example, what does the workspace_id refer to, does it refer to the workspaceId in the Log analytics workspace, or does it refer to a resourceId of that La workspace (/subscription/...)

**Comment by cudeso** [comment]
It's the workspace ID, there's no use of a resource ID. I'll specify it further in the README
