### ISSUE TITLE
Failure Exception: TypeError: string indices must be integers Stack

### ISSUE THREAD

**Issue by Tratino** [cudeso/misp2sentinel#64]
I tried to get the Azure Function running and created the Key Vault secrets. My tenant secret looks like this:

> [{"tenantId": "abcd", "id": "abcd", "secret": "abcd", "workspaceId": "abcd"}]

If the function executes, I get the following error:
`Result: Failure Exception: TypeError: string indices must be integers Stack: File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py", line 479, in _handle__invocation_request call_result = await self._loop.run_in_executor( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py", line 752, in _run_sync_func return ExtensionManager.get_sync_invocation_wrapper(context, File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapper result = function(**args) File "/home/site/wwwroot/MISP2Sentinel/__init__.py", line 115, in main pmain() File "/home/site/wwwroot/MISP2Sentinel/__init__.py", line 105, in pmain push_to_sentinel(item['tenantId'], item['id'], item['secret'], item['workspaceId'])`

I have the latest version from Github deployed. I only have one Tenant. I followed the description in README.MD. The description in INSTALL.MD still contains the old notation of the tenant secret. Any idea what could be wrong?

**Comment by lnfernux** [comment]
I have updated the INSTALL.MD now per your report - thanks for that. 

Trying to reproduce the error (with only one workspace) now.

**Comment by lnfernux** [comment]
@Tratino I can't seem to reproduce it here. Tried with both 1 and 2 workspaces in the object. Is the kv-secret object single line? Multi-line won't work.

**Comment by Tratino** [comment]
That seems to be the issue. I now only get and execution failed error. What can I do to increase the logging to find the problem?

**Comment by Tratino** [comment]
Single Line fixed it. Now the problem seems to be with the MISP Instance.
