### ISSUE TITLE
Only 49 IoC uploaded

### ISSUE THREAD

**Issue by novvy25** [cudeso/misp2sentinel#66]
I am fetching new feeds to MISP everyday and uploading them to Sentinel, but every day I am getting the same output:
misp2sentinel - INFO - Start MISP2Sentinel
misp2sentinel - INFO - Fetching and parsing data from MISP ...
misp2sentinel - INFO - Using Microsoft Upload Indicator API
misp2sentinel - INFO - Received MISP events page 1 with 5 events
misp2sentinel - INFO - Processed 49 indicators
misp2sentinel - INFO - Received 49 indicators in MISP
misp2sentinel - INFO - Start uploading indicators
misp2sentinel - INFO - Indicators sent - request number: 0 / indicators: 49 / remaining: 0
misp2sentinel - INFO - Finished uploading indicators
misp2sentinel - INFO - End MISP2Sentinel
So I have only 49 TI indicators in MS Sentinel from MISP. What am I missing?

**Comment by cudeso** [comment]
Hello @novvy25 ; please check `misp_event_filters`, this describes which events need to be imported.

**Comment by novvy25** [comment]
changed timestamp to 30 days - still getting only 49 indicators

misp_event_filters = {
    "published": 1,
    "tags": [ "workflow:state=\"complete\""],
    "enforceWarninglist": True,
    "includeEventTags": True,
    "publish_timestamp": "30d",
}

**Comment by cudeso** [comment]
Do you get the same results if you try a search via the API (/events/restSearch) with the exact same parameters as in `misp_event_filters`?

**Comment by novvy25** [comment]
Checked by postman
![image](https://github.com/cudeso/misp2sentinel/assets/99868622/f1fd9355-6a26-4145-8095-23602ea7f326)
the response is empty
![image](https://github.com/cudeso/misp2sentinel/assets/99868622/da7759df-7ec5-4eae-95c0-80b6367b9a22)

**Comment by novvy25** [comment]
That did it - thank you

**Comment by cudeso** [comment]
Great!
