### ISSUE TITLE
Rate limiting shouldn't terminate the execution but wait for the rate limit to run out and continue

### ISSUE THREAD

**Issue by Kaloszer** [cudeso/misp2sentinel#67]
Noticed that sometimes when testing I get rate limited getting error code 429- '... try again in {} seconds'.

We should add an automatic wait and retry after said {time} - additionally this should be a warning not an error.

**Comment by cudeso** [comment]
Indeed. Good catch. Will fix address in the next update.

**Comment by Kaloszer** [comment]
@cudeso I've actually added this just now in my fork. I think it should work, just need to validate.
