### ISSUE TITLE
Random 500 errors when posting to https://sentinelus.azure-api.net/{workspaceId}/threatintelligence:upload-indicators?api-version=2022-07-01

### ISSUE THREAD

**Issue by jusso-dev** [cudeso/misp2sentinel#84]
Hey all,

Wondering if anyone knows why I'm getting random empty 500 responses when posting to the above API in the solution? I've inspected the response body and manually crafted an API message but I am unable to determine why I'm getting this response? 

@cudeso any ideas?

**Comment by cudeso** [comment]
Hello,

I've seen this on three occasions:
- If there is a proxy between you and Sentinel which "mangles" the requests
- Temporary hiccups with Sentinel (this happens)
- The Azure App no longer has sufficient permissions or an outdated secret

**Comment by jusso-dev** [comment]
Thanks for that! #1 is not a possibility in my case, but will check the secret again and perms, either way I think we can confirm this is a poor user experience on MS behalf, so have raised a support ticket and will post back here with the outcome.
