### ISSUE TITLE
Azure permission

### ISSUE THREAD

**Issue by ATIOSA** [cudeso/misp2sentinel#85]
Hi! 

I've got a question: « Microsoft Sentinel Contributor » is a high permission. Is it possible to reduce this? Or create a custom rule? In this case, what permissions are needed?

**Comment by cudeso** [comment]
Hello. This permissions is part of the Microsoft requirements, please see: https://learn.microsoft.com/en-us/azure/sentinel/connect-threat-intelligence-upload-api#assign-a-role-to-the-application
