### ISSUE TITLE
Use certificats for API connexion

### ISSUE THREAD

**Issue by ATIOSA** [cudeso/misp2sentinel#87]
Hi, I have a restriction on application connections. I would have to connect to the application via a certificate, not a secret. Would it be possible to add a feature for this case?

**Comment by cudeso** [comment]
Hello,
The MISP2Sentinel integration relies on the setup recommended by Microsoft to get access to the Upload Indicators API, which is via a secret, please see https://learn.microsoft.com/en-us/azure/sentinel/connect-threat-intelligence-upload-api#generate-and-record-client-secret
Access via a certificate is not immediately foreseen in the near future (except fe. if the documentation from Microsoft on the Upload Indicators API would also include it).
