### ISSUE TITLE
Feature Request for Date to be added

### ISSUE THREAD

**Issue by TheOfficalNick** [cudeso/misp2sentinel#88]
Would it be possible to get the Date field added into this? This would be valuable intel as it is indicative of when the event was first added to MISP which means it's the closest date to when the event was observed in the wild.

**Comment by cudeso** [comment]
Good idea! 
Where do you propose to add the date field? In  the description (which already contains the other references to the event)?
Do you refer to the "date" field, or the event publish timestamp?

**Comment by cudeso** [comment]
<img width="288" alt="1" src="https://github.com/cudeso/misp2sentinel/assets/256028/e6d48d95-c876-401c-afdf-e8d8fecff348">

Add date in the description field
