### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by aliman53** [cudeso/misp2sentinel#91]
Hi @cudeso,

Receiving this error when running the script, have the latest version. 

we will officially deprecate python versions below 3.10 on January 1st 2024.
**Please update your codebase.**
  from pymisp import *
Traceback (most recent call last):
  File "script.py", line 2, in <module>
    import config
ModuleNotFoundError: No module named 'config'

![image](https://github.com/cudeso/misp2sentinel/assets/130716674/d9263332-707d-483a-9a98-7bb32b5d67d5)

**Comment by cudeso** [comment]
This means the config.py , the main configuration file, is not present in the directory where you execute the script.
Maybe it's not readable by the user you use to execute the sync, or it has been removed?

**Comment by aliman53** [comment]
Hi I can see the config.py file in the directory, i have not changed any permissions and im executing the script as root user.

**Comment by cudeso** [comment]
Hello. Are you running the script from the directory where the config.py file is stored?

**Comment by aliman53** [comment]
Yes 

Below is the contents of the directory i'm running out of:
![image](https://github.com/cudeso/misp2sentinel/assets/130716674/a2d940f2-6e5f-446b-8acf-13e5b66aaf3e)

**Comment by aliman53** [comment]
Thank you, works now :)
