### ISSUE TITLE
Graph API to Defender ATP error in logs

### ISSUE THREAD

**Issue by aliman53** [cudeso/misp2sentinel#92]
Hi, 

I'm using the graph API to try push IOCs to Defender ATP, i've set up the config.py file to only include the Graph API supported sections. 

When running the script and checking the logs in /tmp I can see there is a response error but not sure what the exact details of this error are. Is there a way to see further details of this error? 

![image](https://github.com/cudeso/misp2sentinel/assets/130716674/03fd0d58-1d0e-4dfe-8fd3-df85c1eb0222)

**Comment by cudeso** [comment]
There's one indicator synchronised and one not. This means the sync connection work.
The error is most likely an indicator type of MISP not supported by Sentinel (fe. YARA or Sigma rules). Check the folder "log", there should be an output of the JSON error.
If not, also set `write_post_json` and `verbose_log` to True and run the script again.

**Comment by cudeso** [comment]
Closing pending feedback
