### ISSUE TITLE
PyMISP error-This class is deprecated, use PyMISP instead

### ISSUE THREAD

**Issue by Prab2010** [cudeso/misp2sentinel#96]
During the Pymisp execution, script.py throws  the following error : 

**/home/ubuntu/misp2sentinel/PyMISP/pymisp/__init__.py:67: FutureWarning: This class is deprecated, use PyMISP instead
  warnings.warn('This class is deprecated, use PyMISP instead', FutureWarning).**

Also tried upgrading the pymisp using pip3 install --upgrade pymisp and this the output of pip show pymisp: 
Name: pymisp
Version: 2.4.193
Summary: Python API for MISP.
Home-page: https://github.com/MISP/PyMISP
Author: Raphaël Vinot
Author-email: raphael.vinot@circl.lu
License: BSD-2-Clause
Location: /home/ubuntu/misp2sentinel/sentinel/lib/python3.10/site-packages
Requires: deprecated, publicsuffixlist, python-dateutil, requests
Required-by: misp-stix

Any thoughts ? the scripts is installed and executed as same user too.

**Comment by cudeso** [comment]
Hello. It's a warning, it should not prevent the script from executing properly.
